### ISSUE TITLE
Block anchor is not shown in the Top News / ブロックアンカーがトップニュースに表示されない

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#62]
例: 「はくたか」で検索
以下のCSSを適用すれば解消される・・・が自信がないので一旦は保留

```css
.ttfMne {
    height: auto !important;
}
```
